package com.example.twoforyou_boardgamedatabase.ui.display.util

import android.util.Log

fun getKoreanNameOfMechanismItem(mechanism: String): String {
    return when (mechanism) {
        "Acting" -> "연기"
        "Action Drafting" -> "액션 드래프팅"
        "Action Points" -> "액션 포인트"
        "Action Queue" -> "액션 순서 정렬"
        "Action Retrieval" -> "액션 회수"
        "Action Timer" -> "액션 타이머"
        "Action/Event" -> "액션/이벤트"
        "Advantage Token" -> "어드밴티지 토큰"
        "Alliances" -> "연합"
        "Area Majority / Influence" -> "영향력"
        "Area Movement" -> "지역 이동"
        "Area-Impulse" -> "지역 내 충돌"
        "Auction Compensation" -> "패찰 보상"
        "Auction: Dexterity" -> "경매: 덱스터리티"
        "Auction: Dutch" -> "더치 경매"
        "Auction: Dutch Priority" -> "역경매"
        "Auction: English" -> "영국식 경매"
        "Auction: Fixed Placement" -> "고정 배치 경매"
        "Auction: Multiple Lot" -> "다수 판매 경매"
        "Auction: Once Around" -> "한 바퀴 경매"
        "Auction: Sealed Bid" -> "비밀 경매"
        "Auction: Turn Order Until Pass" -> "패스까지 차례순 경매"
        "Auction/Bidding" -> "경매/입찰"
        "Automatic Resource Growth" -> "자원 자동 증가"
        "Betting and Bluffing" -> "배팅&블러핑"
        "Bias" -> "시간적 이동"
        "Bids As Wagers" -> "내기 배팅"
        "Bingo" -> "빙고"
        "Bribery" -> "뇌물"
        "Campaign / Battle Card Driven" -> "캠페인/전쟁 카드"
        "Card Play Conflict Resolution" -> "카드 충돌 해결"
        "Catch the Leader" -> "1등잡기"
        "Chaining" -> "체인 확장 타일"
        "Chit-Pull System" -> "순서 랜덤 결정"
        "Closed Drafting" -> "비공개 드래프팅"
        "Closed Economy Auction" -> "폐쇄 경매"
        "Command Cards" -> "명령 카드"
        "Commodity Speculation" -> "상품 투기"
        "Communication Limits" -> "소통 제한"
        "Connections" -> "지점 연결"
        "Constrained Bidding" -> "조합 제한 입찰"
        "Contracts" -> "계약"
        "Cooperative Game" -> "협동/협력"
        "Crayon Rail System" -> "경로 그리기"
        "Critical Hits and Failures" -> "주사위 목표"
        "Cube Tower" -> "큐브 떨어트리기"
        "Deck Construction" -> "덱 구성"
        "Deck, Bag, and Pool Building" -> "덱/백/풀 빌딩"
        "Deduction" -> "디덕션"
        "Delayed Purchase" -> "지연 구매"
        "Dice Rolling" -> "주사위"
        "Die Icon Resolution" -> "주사위 아이콘 해결"
        "Different Dice Movement" -> "주사위 이동"
        "Drawing" -> "그리기"
        "Elapsed Real Time Ending" -> "실제 시간 기반"
        "Enclosure" -> "울타리"
        "End Game Bonuses" -> "게임 종료 보너스"
        "Events" -> "이벤트"
        "Finale Ending" -> "최종 승자 게임"
        "Flicking" -> "알까기"
        "Follow" -> "행동 따라하기"
        "Force Commitment" -> "강제 실행"
        "Grid Coverage" -> "그리드 덮기"
        "Grid Movement" -> "그리드 이동"
        "Hand Management" -> "핸드 관리"
        "Hexagon Grid" -> "육각형 그리드"
        "Hidden Movement" -> "비공개 이동"
        "Hidden Roles" -> "비공개 역할"
        "Hidden Victory Points" -> "비공개 승점"
        "Highest-Lowest Scoring" -> "최고/최저 승점"
        "Hot Potato" -> "폭탄 돌리기"
        "I Cut, You Choose" -> "케이크 자르기"
        "Impulse Movement" -> "구간 이동"
        "Income" -> "수입"
        "Increase Value of Unchosen Resources" -> "미선택 자원 가치 증가"
        "Induction" -> "규칙 파악"
        "Interrupts" -> "차례 진행 방해"
        "Investment" -> "투자"
        "Kill Steal" -> "막타"
        "King of the Hill" -> "위치 차지"
        "Ladder Climbing" -> "클라이밍"
        "Layering" -> "겹치기"
        "Legacy Game" -> "레거시"
        "Line Drawing" -> "선 그리기"
        "Line of Sight" -> "가시선"
        "Loans" -> "대출"
        "Lose a Turn" -> "턴 잃기"
        "Mancala" -> "만칼라"
        "Map Addition" -> "맵 추가"
        "Map Deformation" -> "맵 변형"
        "Map Reduction" -> "맵 축소"
        "Market" -> "시장"
        "Matching" -> "매칭"
        "Measurement Movement" -> "측정 이동"
        "Melding and Splaying" -> "혼합/조합"
        "Memory" -> "메모리"
        "Minimap Resolution" -> "미니맵 충돌 해결"
        "Modular Board" -> "조립식 보드"
        "Move Through Deck" -> "덱 진행"
        "Movement Points" -> "이동 포인트"
        "Movement Template" -> "이동 템플릿"
        "Moving Multiple Units" -> "다중 요닛 이동"
        "Multi-Use Cards" -> "카드 행동 선택"
        "Multiple Maps" -> "다중 맵"
        "Narrative Choice / Paragraph" -> "이야기/단락 선택"
        "Negotiation" -> "협상"
        "Neighbor Scope" -> "인접 자원 공유"
        "Network and Route Building" -> "네트워크"
        "Once-Per-Game Abilities" -> "게임당 1번"
        "Open Drafting" -> "오픈 드래프팅"
        "Order Counters" -> "순서 카운터"
        "Ordering" -> "정렬"
        "Ownership" -> "소유권"
        "Paper-and-Pencil" -> "종이와 연필"
        "Passed Action Token" -> "액션 토큰 전달"
        "Pattern Building" -> "패턴 빌딩"
        "Pattern Movement" -> "패턴 이동"
        "Pattern Recognition" -> "패턴 인식"
        "Physical Removal" -> "물리적 제거"
        "Pick-up and Deliver" -> "자원 운송"
        "Pieces as Map" -> "조각 맵"
        "Player Elimination" -> "플레이어 제거"
        "Player Judge" -> "플레이어 심판"
        "Point to Point Movement" -> "선 이동"
        "Predictive Bid" -> "예측 입찰"
        "Prisoner's Dilemma" -> "죄수의 딜레마"
        "Programmed Movement" -> "프로그래밍된 이동"
        "Push Your Luck" -> "운빨"
        "Questions and Answers" -> "질문과 답변"
        "Race" -> "레이스"
        "Random Production" -> "무작위 생산"
        "Ratio / Combat Results Table" -> "비율/전투 결과 표"
        "Re-rolling and Locking" -> "다시 굴리기 및 잠금"
        "Real-Time" -> "리얼 타임"
        "Relative Movement" -> "상대적 이동"
        "Resource Queue" -> "자원 대기열"
        "Resource to Move" -> "이동하는 자원"
        "Rock-Paper-Scissors" -> "가위 바위 보"
        "Role Playing" -> "롤 플레잉"
        "Roles with Asymmetric Information" -> "비대칭 정보 역할"
        "Roll / Spin and Move" -> "굴리기/돌리기와 이동"
        "Rondel" -> "론델"
        "Scenario / Mission / Campaign Game" -> "시나리오/미션/캠페인"
        "Score-and-Reset Game" -> "점수 계산 후 리셋"
        "Secret Unit Deployment" -> "비밀유닛 배치"
        "Selection Order Bid" -> "선택 순서 입찰"
        "Semi-Cooperative Game" -> "반협력"
        "Set Collection" -> "셋 컬렉션"
        "Simulation" -> "시뮬레이션"
        "Simultaneous Action Selection" -> "동시 액션 선택"
        "Singing" -> "노래 부르기"
        "Single Loser Game" -> "꼴찌 가르기"
        "Slide/Push" -> "밀기/당기기"
        "Solo / Solitaire Game" -> "솔로"
        "Speed Matching" -> "속도 맞추기"
        "Spelling" -> "스펠링"
        "Square Grid" -> "사각형 그리드"
        "Stacking and Balancing" -> "밸런스"
        "Stat Check Resolution" -> "스탯 체크 해결"
        "Static Capture" -> "고정 포획"
        "Stock Holding" -> "주식 보유"
        "Storytelling" -> "스토리텔링"
        "Sudden Death Ending" -> "특정 조건 종료"
        "Tags" -> "태그"
        "Take That" -> "빼앗기"
        "Targeted Clues" -> "대상 단서"
        "Team-Based Game" -> "팀"
        "Tech Trees / Tech Tracks" -> "테크트리"
        "Three Dimensional Movement" -> "3차원 이동"
        "Tile Placement" -> "타일 놓기"
        "Track Movement" -> "트랙 이동"
        "Trading" -> "거래"
        "Traitor Game" -> "배신자"
        "Trick-taking" -> "트릭테이킹"
        "Tug of War" -> "줄다리기"
        "Turn Order: Auction" -> "턴오더: 입찰"
        "Turn Order: Claim Action" -> "턴오더: 액션 선택"
        "Turn Order: Pass Order" -> "턴오더: 패스 순서"
        "Turn Order: Progressive" -> "턴오더: 시계 방향"
        "Turn Order: Random" -> "턴오더: 랜덤"
        "Turn Order: Role Order" -> "턴오더: 역할"
        "Turn Order: Stat-Based" -> "턴오더: 스탯"
        "Turn Order: Time Track" -> "턴오더: 시간 순서"
        "Variable Phase Order" -> "변경 가능한 단계 순서"
        "Variable Player Powers" -> "비대칭 플레이어 능력"
        "Variable Set-up" -> "변경 가능한 셋업"
        "Victory Points as a Resource" -> "승점을 자원으로"
        "Voting" -> "투표"
        "Worker Placement" -> "일꾼놓기"
        "Worker Placement with Dice Workers" -> "주사위 일꾼놓기"
        "Worker Placement, Different Worker Types" -> "다른 형태의 일꾼놓기"
        "Zone of Control" -> "통제 구역"
        else -> {
            Log.d("TAG", "Mechanism: ${mechanism}")
            "에러"
        }
    }
}